/**
 * Icones do app: um vocabulario so, do lucide. Importar daqui e nao do pacote,
 * para o mesmo conceito ter sempre o mesmo desenho (e o bundle so levar estes).
 */
export {
  ArrowDownToLine as IconeOrientacao,
  Factory as IconeProducao,
  List as IconeLista,
  Package as IconeMaterial,
  Palette as IconeEstilo,
  PanelTop as IconeChapa,
  Percent as IconeMargem,
  Ruler as IconeMedidas,
  Sparkles as IconeAcabamento,
  Trash as IconeExcluir,
  TriangleAlert as IconeAtencao,
  Box as IconeCaixa,
  Check as IconeOk,
  ChevronDown as IconeAbaixo,
  ChevronRight as IconeDireita,
  Copy as IconeCopiar,
  Download as IconeBaixar,
  FileUp as IconeAbrir,
  FilePlus as IconeNovo,
  Focus as IconeEnquadrar,
  Info as IconeInfo,
  Layers as IconeCamadas,
  LayoutGrid as IconeArrumar,
  Lock as IconeTravado,
  Plus as IconeMais,
  Eraser as IconeSuavizar,
  Group as IconeAgrupar,
  Ungroup as IconeDesagrupar,
  Eye as IconeVisivel,
  EyeOff as IconeOculto,
  SquareDashedMousePointer as IconeSelecionarTudo,
  FolderClosed as IconeGrupo,
  FolderOpen as IconeGrupoAberto,
  LockOpen as IconeDestravado,
  Maximize2 as IconeTamanho,
  MousePointer2 as IconeSelecionar,
  Move as IconeMover,
  OctagonX as IconePerigo,
  PenTool as IconeDesenhar,
  Printer as IconeImprimir,
  Receipt as IconeOrcamento,
  RotateCcw as IconeDesfazer,
  RotateCw as IconeGirar,
  Rows3 as IconeMontagem,
  Type as IconeTexto,
  Undo2 as IconeOriginal,
  X as IconeFechar,
} from 'lucide-react';

export type { LucideIcon as Icone } from 'lucide-react';
